"""
Django settings for SchoolProject project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hq#x)9d-9o3kvlm4$7zi*0(*75ag!w2!+sly))e@7++%f%jl3c'
FERNET_KEY = 'YpHvX2mAOOy8EsrVo8yDdXd3Wry0zR1ibGlA7dYo6X8='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.ngrok-free.app']
# ALLOWED_HOSTS = ['arsDemo.com']
ALLOWED_HOSTS = ['testramon02', '127.0.0.1', 'localhost']

# csrf
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1', 'https://127.0.0.1', 'http://localhost','https://localhost', 'https://testramon02', 'http://testramon02']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'AgileReserveSys',
    'sslserver'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AgileReserveSysProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
             # Add the path to the root 'templates' directory
            os.path.join(BASE_DIR, 'templates'),

            # Add the path to the 'normal_templates' directory
            os.path.join(BASE_DIR, 'AgileReserveSys', 'templates', 'normal_templates'),

            # Add the path to the 'active_templates' directory
            os.path.join(BASE_DIR, 'AgileReserveSys', 'templates', 'active_templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AgileReserveSysProject.wsgi.application'

AUTH_USER_MODEL = "AgileReserveSys.CustomUser"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
#   'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     },
#   'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'School',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': 'localhost',  # or your MySQL server's hostname
#         'PORT': '3306',       # or your MySQL server's port
#     },
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'AgileReserve',
        'USER': 'postgres',
        # 'PASSWORD': '123',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',  # or your PostgreSQL server's hostname
        'PORT': '5432',       # or your PostgreSQL server's port
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Configure static files (CSS, JavaScript, Images, etc.)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Configure media files (user uploaded files, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'

LOGOUT_REDIRECT_URL = '/'

APPEND_SLASH = True

PASSWORD_RESET_TIMEOUT = 300 # seconds

# Recaptcha
RECAPTCHA_PUBLIC_KEY = '6LeKOMwnAAAAABqc3fdeiiGi3pMD--mhfgavn2Ii'
RECAPTCHA_PRIVATE_KEY = '6LeKOMwnAAAAAMCgD3zUQyq4EF64ddSYdM_uxgTd'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

# Mail
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = BASE_DIR / "sent_emails"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = ""
DEFAULT_CONTACT_EMAIL = ""
EMAIL_USE_TLS = True
EMAIL_PORT = 587
# EMAIL_PORT = 465
EMAIL_USE_SSL = False

# If you're using HTTPS
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SESSION_COOKIE_SECURE = True